version: '3'

volumes:
  postgres_data:
services:
  db:
    image: postgres
    env_file: ./task_manager_api/.env
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    expose:
    - "5432"
  web:
    build: .
    env_file: ./task_manager_api/.env
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
