version: '3'

volumes:
  postgres_data:
  data:
services:
  db:
    image: postgres
    env_file: ./task_manager_api/.env
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    expose:
    - "5432"
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./task_manager_api/.env
    volumes:
      - .:/code
      - /var/log/task_manager_api/:/var/log/task_manager_api/
    ports:
      - "80:8000"
    depends_on:
      - db
  bot:
    build:
      context: .
      dockerfile: ./docker_bot
    command: bash ./bot_launch.sh
    depends_on:
      - web
    volumes:
      - data:/var/data/
    env_file: ./task_manager_api/.env
