# Generated by Django 2.2.3 on 2019-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('TO_DO', 'To Do'), ('DONE', 'Done')], default='TO_DO', max_length=20),
        ),
    ]
