# Generated by Django 2.2.3 on 2019-07-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification',
            field=models.DateTimeField(null=True),
        ),
    ]
